Review/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.password, name="password"),
    path('<int:user_id>/', views.profile, name='profile'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

Review/community/urls.py
from django.urls import path
from . import views


app_name = 'community'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/update/', views.update, name = 'update'),
    path('<int:review_pk>/delete/', views.delete, name = 'delete'),
    path('<int:review_pk>/comment', views.comments_create, name='comments_create'),
    path('<int:review_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name = 'comments_delete'),
    path('<int:review_pk>/like/', views.like, name='like'),
]

Review/pjt07/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from community import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('accounts/', include('accounts.urls'),),
    path('community/', include('community.urls'),),
    path('accounts/', include('allauth.urls'),),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Review/pjt07/templates/base.html
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% bootstrap_css %}
  <title>PJT07</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
</head>
<body>
  {% include 'nav.html' %}
  <div class="container">
    {% block content %}

    {% endblock %}
  </div>
  {% bootstrap_javascript %}
</body>
</html>

Review/pjt07/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid d-flex justify-content-start align-items-center">
    <a class="navbar-brand p-0 d-flex justify-content-start align-items-center" href="{% url 'community:index' %}"><i class="fas fa-home"></i></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex justify-content-start align-items-center" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <form class="nav-link" action="{% url 'community:index' %}" method="GET">
            <button type="submit" class="btn btn-light"><i class="fas fa-indent"></i> INDEX</button>
          </form>
        </li>
        <li class="nav-item">
          <form class="nav-link" action="{% url 'community:create' %}" method="GET">
            <button type="submit" class="btn btn-light"><i class="fas fa-edit"></i> CREATE</button>
          </form>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <form class="nav-link" action="{% url 'accounts:profile' request.user.pk %}" method="GET">
              <button type="submit" class="btn btn-light"><i class="fas fa-user-circle"></i> MY PROFILE</button>
            </form>
          </li>
          <li class="nav-item">
            <form class="nav-link" action="{% url 'accounts:update' %}" method="GET">
              <button type="submit" class="btn btn-light">회원정보수정</button>
            </form>
          </li>
          <li class="nav-item">
            <form class="nav-link" action="{% url 'accounts:logout' %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn btn-light">로그아웃</button>
            </form>
          </li>
          <li class="nav-item">
            <form class="nav-link" action="{% url 'accounts:delete' %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn btn-light">탈퇴</button>
            </form>
          </li>
        {% else %}
          <li class="nav-item">
            <form class="nav-link" action="{% url 'accounts:login' %}" method="GET">
              <button type="submit" class="btn btn-light">로그인</button>
            </form>
          </li>
          <li class="nav-item">
            <form class="nav-link" action="{% url 'accounts:signup' %}" method="GET">
              <button type="submit" class="btn btn-light">회원가입</button>
            </form>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>