Review/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.password, name="password"),
    path('<int:user_id>/', views.profile, name='profile'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

Review/community/urls.py
from django.urls import path
from . import views


app_name = 'community'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/update/', views.update, name = 'update'),
    path('<int:review_pk>/delete/', views.delete, name = 'delete'),
    path('<int:review_pk>/comment', views.comments_create, name='comments_create'),
    path('<int:review_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name = 'comments_delete'),
    path('<int:review_pk>/like/', views.like, name='like'),
]

Review/pjt07/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from community import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('accounts/', include('accounts.urls'),),
    path('community/', include('community.urls'),),
    path('accounts/', include('allauth.urls'),),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Review/community/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from imagekit.processors import Thumbnail

class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    title = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=50)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(processors = [ResizeToFill(600, 600)], format='JPEG', options={'quality': 90})

    def __str__(self):
        return self.title

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

    def __str__(self):
        return self.content

Review/community/forms.py
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        exclude = ('user', 'like',)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ('user', 'review',)

Review/community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from .models import Review, Comment
from .forms import ReviewForm, CommentForm
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    reviews = Review.objects.order_by('-pk')
    paginator = Paginator(reviews, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'reviews' : reviews,
        'page_obj': page_obj,
    }
    return render(request, 'community/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('community:detail', review.pk)
    else:
        form = ReviewForm()
    context = {
        'form': form
    }
    return render(request, 'community/create.html', context)

@login_required
def detail(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comments = review.comment_set.order_by('-pk')
    comment_form = CommentForm()
    context = {
        'review': review,
        'comment_form': comment_form,
        'comments': comments
    }
    return render(request, 'community/detail.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def update(request, review_pk):
    review = get_object_or_404(Review, pk = review_pk)
    if request.user == review.user:
        if request.method == 'POST':
            form = ReviewForm(request.POST, request.FILES, instance = review)
            if form.is_valid():
                form.save()
                return redirect('community:detail', review.pk)
        else:
            form = ReviewForm(instance = review)
    else:
        return redirect('community:index')
    context = {
        'form':form,
        'review':review,
    }
    return render(request, 'community/update.html', context)

@require_POST
def delete(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.user.is_authenticated:
        if request.user == review.user:
            review.delete()
            return redirect('community:index')
    return redirect('community:detail', review.pk)

@require_POST
def comments_create(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.review = review
            comment.user = request.user
            comment.save()
            return redirect('community:detail', review.pk)
        context = {
            'comment_form': comment_form,
            'review': review,
        }
        return render(request, 'community/detail.html', context)
    return redirect('accounts:login')

@require_POST
def comments_delete(request, review_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user.is_authenticated:
        if request.user == comment.user:
            comment.delete()
    return redirect('community:detail', review_pk)

@require_POST
def like(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        if review.like.filter(pk=request.user.pk).exists():
            review.like.remove(request.user)
        else:
            review.like.add(request.user)
        return redirect('community:detail', review.pk)
    return redirect('accounts:login')

Review/community/templates/community/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1 class="fw-bold">CREATE PAGE</h1>
  <hr>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'community:index' %}" class="btn btn-light">BACK</a>
{% endblock %}

Review/community/templates/community/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load humanize %}

{% block content %}
  <h1 class="fw-bold">DETAIL PAGE</h1>
  <hr>
  <div class="container">
    <div class="row d-flex justify-content-between">
      <div class="col d-flex flex-column justify-content-between">
        <div class="row">        
          <a href="{% url 'accounts:profile' review.user.pk %}" class="fs-4 text-dark fw-bold text-decoration-none">Creator : {{ review.user }}</a><br>
          <br>
          <p class="fs-4">Review Title : {{ review.title }}</p>
          <p class="fs-4">Movie Title : {{ review.movie_title }}</p>
          <p class="fs-4">Review Content : {{ review.content }}</p>
          <p class="fs-4">Rank : {{ review.rank }}</p>
          <p class="fs-4">Created at : {{ review.created_at|naturalday }}</p>
          <p class="fs-4">Edit at : {{ review.updated_at|naturaltime }}</p>
        </div>
        
        <div class="row d-flex flex-row justify-content-end">
          <div class="col">
            <a href="{% url 'community:index' %}" class="btn btn-light btn-lg mb-3">BACK <i class="fas fa-undo"></i></a>
          </div>
          {% if request.user == review.user %}
            <div class="col">
            <a href="{% url 'community:update' review.pk %}" class="btn btn-primary btn-lg mb-3">EDIT <i class="far fa-edit"></i></a>
            </div>
            <div class="col">
            <form action="{% url 'community:delete' review.pk %}" method = "POST" class="mb-3">
              {% csrf_token %}
              <button class="btn btn-danger btn-lg"> DELETE <i class="far fa-trash-alt"></i></button>
            </form>  
            </div>
          {% endif %}
        </div>
      </div>
      <div class="col">
        {% if review.image %}
          <img src="{{review.image.url}}" alt="{{review.image}}">
        {% endif %}
      </div>
    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col">
      <form action="{% url 'community:like' review.pk %}" method="POST">
        {% csrf_token %}
        {% if request.user in review.like.all %}
          <button class="btn btn-link text-decoration-none">
            <i class="fas fa-heart fa-lg mx-3" style="color:crimson;"></i>  
            <span class="fs-5 fw-bold text-dark">LIKE CANCEL</span>
          </button> 
        {% else %} 
          <button class="btn btn-link text-decoration-none">
            <i class="fas fa-heart fa-lg mx-3" style="color:black;"></i>
            <span class="fs-5 fw-bold text-dark">LIKE</span>
          </button>
        {% endif %}
      </form>
    </div>
    <div class="col d-flex flex-row justify-content-end align-items-center">
      <span class="fw-bold fs-5">{{review.like.all|length}}명이 좋아합니다</span>
    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col d-flex flex-row align-items-center">
      <i class="far fa-comment-alt mx-4 fa-lg" style="color:black;"></i>
      <span class="fs-5 fw-bold"> 댓글 </span>
    </div>
    <div class="col d-flex flex-row justify-content-end align-items-center">
      <p class="fs-5 fw-bold">{{ comments|length }}개의 댓글이 있습니다</p>
    </div>
  </div>

  <ul>
    {% for comment in comments %}
      <li>
        {{ comment.content }}
        {{comment.user}}
        {% if request.user == comment.user %}
        <form action="{% url 'community:comments_delete' review.pk comment.pk %}" method="POST">
          {% csrf_token %}
          <input type="submit" value ="DELETE">
        </form>
      {% endif %}  
      </li>
    {% comment %} {% empty %} {% endcomment %}
      {% comment %} <p>댓글이 아직 존재하지 않습니다.</p> {% endcomment %}
    {% endfor %}
  </ul>
 
  {% if request.user.is_authenticated %}
    <form action="{% url 'community:comments_create' review.pk %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form comment_form %}
      <input type="submit" value ="CREATE" class="mt-3">
    </form>
  {% endif %}

{% endblock %}

Review/community/templates/community/index.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load bootstrap_pagination %}

{% block content %}
  <h1 class="fw-bold">INDEX PAGE</h1>
  <hr>
  {% for review in page_obj %}
    <div class="row d-flex justify-content-around">
      <div class="col">
        <p><a href="{% url 'accounts:profile' review.user.pk %}" class="text-dark">Creator : {{ review.user }}</a></p>
        <p>Review Number : {{ review.pk }}</p>
        <p>Review Title :
          <a href="{% url 'community:detail' review.pk %}" class="text-dark">{{ review.title }}</a>
        </p>
        <p>Movie Title : {{ review.movie_title }}</p>
        <p><i class="fas fa-heart fa-lg" style="color:crimson;"></i> {{review.like.all|length}} LIKES</p>
        <a href="{% url 'community:detail' review.pk %}" class="btn btn-light">DETAIL</a>
      </div>
      <div class="col d-flex justify-content-end">
        {% if review.image %}
          <img src="{{review.image.url}}" alt="{{review.image}}" class="w-50 h-90">
        {% endif %}
      </div>
    </div>
    <hr>
  {% endfor %}

  <div class="d-flex justify-content-center">
    {% bootstrap_paginate page_obj range=5 %}
  </div>

{% endblock %}

Review/community/templates/community/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1 class="fw-bold">UPDATE PAGE</h1>
  <hr>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="REVIEW UPDATE">
  </form>
  <hr>
  <a href="{% url 'community:index' %}" class="btn btn-light">BACK</a>
{% endblock %}